### ISSUE TITLE
[App] Update all image names + remove unused assets

### ISSUE THREAD

**Issue by jamesmontemagno** [Microsoft/mvp#17]
To help with the open source process we should standardize and correctly fix all of the image assets in the app:

https://github.com/Microsoft/mvp/blob/master/MobileAppGuidelines.md

Additionally, all of the weird data bindings should be removed to normal Images unless they are dynamic. All the static ones can do something like this:

```
 <Image         
			    Aspect="AspectFill"			
			    HorizontalOptions="Fill"
                VerticalOptions="StartAndExpand">
                <Image.Source>
                    <OnPlatform                    
                        x:TypeArguments="ImageSource"        
                        Android="placeholder.png"
                        iOS="placeholder.png"
                        WinPhone="Assets\placeholder.png"/>
                </Image.Source>
            </Image>
```

**Comment by sthewissen** [comment]
Cleaned up a lot of this in #15. Needs to be tested on all platforms though.
