### ISSUE TITLE
[Question] Settings page

### ISSUE THREAD

**Issue by sthewissen** [Microsoft/mvp#19]
What's the deal with this page? Currently it has only 2 functionalities:

- About
- Logout

These could also be done by making an icon for each in the navigation bar (at least that's how I'd do it on iOS). If there are more settings related things coming in the near future I would create a screen for it using a TableView on iOS which as become the standard there. I believe Android uses a similar standard @jamesmontemagno?

![image](https://user-images.githubusercontent.com/2419439/30758718-ce87cd8e-9fd3-11e7-870f-c5959e274cfb.png)

**Comment by jamesmontemagno** [comment]
So I think it should actually just be an "About Page" with the logo at the top, info about the app with version number and copyright and then at the bottom a button to log out.

**Comment by jamesmontemagno** [comment]
I will take this one on to re-do

**Comment by sthewissen** [comment]
I also wouldn't necessarily open this modally.

**Comment by jamesmontemagno** [comment]
Well since tabs are the root on iOS, it should be modal. On Android/UWP it should be pushed :)

**Comment by sthewissen** [comment]
Ok, I'd opt for a simple white navbar/background on iOS then :)

**Comment by jamesmontemagno** [comment]
yeah for sure. I think we can use the "MVPNavigationPage" everywhere and just customize it per platform. This will make it really easy :)

**Comment by jamesmontemagno** [comment]
I have now completely re-done it. It is more of an about page with a logout on the bottomw
