### ISSUE TITLE
[Question] Profile page

### ISSUE THREAD

**Issue by sthewissen** [Microsoft/mvp#21]
Are there any specs we can use to see what is going on on this page? I'm no MVP myself so I have no idea what kind of stuff is being displayed here or what else we can pull out of the API. That would make it a lot easier to start thinking towards how we can put that information on screen. 

I did an iOS style mockup with what I know is being displayed on there but this is just something I made up. Could use some discussion to create a final direction for this screen :)

<img width="403" alt="screen shot 2017-09-22 at 21 08 46" src="https://user-images.githubusercontent.com/2419439/30760480-9648624c-9fda-11e7-9e3b-90ee8cfbaac9.png">

**Comment by sthewissen** [comment]
I only just now see that recent activities == contributions, so that part can be scrapped from this screen I suppose. They are two distinctly different functionalities that should be separate in their own tabs.

**Comment by jamesmontemagno** [comment]
I have implemented some design time data and added how to get to it here: https://github.com/jamesmontemagno/mvp/blob/2c75e7b2466ce1526f4c6d0b33c81fe4750ffcf4/MobileAppGuidelines.md

I think this is pretty close. I think think that yeah activities == contributions so that can be removed, but I think you nailed it most likely on the UI part. The one thing is that the categories could get a bit long... but i think probably pretty good.

I think that we should see what @jialge has to say as far as the design and what all should go on this page.

**Comment by scottge-msft** [comment]
I like it.  It's much cleaner than my design.  :) :)

Activity == contributions.  Now that we put Contributoins in the tab, we can remove 'Recent Activities'. 

You may consider adding MVPID to the top section. 
https://github.com/Microsoft/mvp/issues/9
Each MVP has a unique ID.   They need to access this ID in many cases.  It will be handy to show the ID on their profile.   The ID  is in the form of MVP134224.

**Comment by sthewissen** [comment]
We could probably put the MVP # below the profile pic.

**Comment by sthewissen** [comment]
I tried to create an alternative to the screen I created above. The attempt above is pretty iOS minded and I wanted to create something that might be a bit more cross-platform in its look and feel. I'd love to hear some comments. Here's a comparison shot between the two:

![screen shot 2017-09-25 at 09 44 38](https://user-images.githubusercontent.com/2419439/30797380-17e00222-a1d6-11e7-9ad3-fed5a75bcbfb.png)

**Comment by sthewissen** [comment]
Perhaps we also need to swap the tabs. For an MVP using the app his contributions and managing them is probably the most important feature. He knows who he is and what his profile looks like :)

**Comment by jamesmontemagno** [comment]
I think that the second option brings in some flare maybe, but I wouldn't do the V thingy, and just have the bottom part be the MVP blue, will make it easier and scale across devices better.

**Comment by Depechie** [comment]
Each design will have it's pro and con and depending on the viewer, there will be preference differences too :)
So my 2 cents... I like the first proposal of Steven the best, somehow I'm no fan of placing data in the center.

**Comment by Depechie** [comment]
Big note also, in the current released app, multiple award categories are just listed with a ',' between them.
Please change this and put them underneath each other!

**Comment by sthewissen** [comment]
This is basically implemented, except for the comment I left in #9.
