### ISSUE TITLE
[App] Remove Custom Renderers for iOS/Android for Contribution Data Entry

### ISSUE THREAD

**Issue by jamesmontemagno** [Microsoft/mvp#23]
There are several custom renderers inside of iOS/Android that make the apps look like Windows applications. We should use standard data entry types on each platform.

**Comment by sthewissen** [comment]
Simply removed these for iOS. Will probably be obsolete anyway once the Add/Edit Contribution screen is visually overhauled.

**Comment by jamesmontemagno** [comment]
Doing the same now on Android:
![image](https://user-images.githubusercontent.com/1676321/30888425-8102c82a-a2ee-11e7-81ff-fd8b5a0f5ff2.png)

Looks 100% better!
