### ISSUE TITLE
[Suggestion] App name

### ISSUE THREAD

**Issue by sthewissen** [Microsoft/mvp#30]
Just a suggestion that @jfversluis came up with:

Perhaps we should rename the app to something short and sweet. Currently the name on my iOS app overview screen is "Microsoft..." which doesn't tell you a whole lot. Suggestion was to maybe rename it to "MVPBuzz" to also link into the hashtag on Twitter. What do you guys think?

**Comment by jamesmontemagno** [comment]
I think just MVP

**Comment by sthewissen** [comment]
Works for me!

**Comment by scottge-msft** [comment]
Adding @KerryHerger to see if he has anything to add :)
