### ISSUE TITLE
[Suggestion] Activities vs. contributions

### ISSUE THREAD

**Issue by sthewissen** [Microsoft/mvp#32]
The official MVP site calls everything activities, we call it contributions. We've settled on the fact that they're one and the same, but I would suggest following suit with the actual MVP site and calling them activities. That way no gets confused and everybody is happy.

![screen shot 2017-10-03 at 08 52 43](https://user-images.githubusercontent.com/2419439/31114065-8ad142cc-a81c-11e7-8a64-e7f61aeb052c.png)

**Comment by jamesmontemagno** [comment]
Yeah, i think it should align.

**Comment by sthewissen** [comment]
This was done in the UI in #32 except for the actual filenames/classnames. Will do that in an upcoming PR.
