### ISSUE TITLE
[Bug] Opening an activity for editing and then adding sets edit values

### ISSUE THREAD

**Issue by sthewissen** [Microsoft/mvp#33]
- Open an activity for editing
- Close it
- Click on the Add activity button

**Result:**
The values for the activity you opened for editing are shown.

**Comment by sthewissen** [comment]
This is due to the fact that all the ViewModels are set up as singletons which means this doesn't get initialised again or emptied out. Do we even want to keep this singleton approach to the ViewModels around? I'm not necessarily a fan of it. What about you @jamesmontemagno?

**Comment by jamesmontemagno** [comment]
They shouldn't be singletons, i am not a fan to be honest with you.

**Comment by sthewissen** [comment]
Then they’re vetod out I suppose :)
