### ISSUE TITLE
[Design] Login page

### ISSUE THREAD

**Issue by aloisdeniel** [Microsoft/mvp#37]
Maybe we can improve onboarding experience by having a better authentication page.

As soon as everyone validate the design I will implement it.

### Suggestion

![mvp-design-login](https://user-images.githubusercontent.com/7687231/31202905-ec72d02e-a964-11e7-9e53-d6a332e98d6d.png)

### Associated resources 

* Background image : [Unsplash](https://unsplash.com/photos/CqBjlUs6t50) *(maybe an official Microsoft branded image could be better here)*
* Blue layer : `#0072c6` / Opacity: `0.85`
* "Learn more" button background : `#FFFFFF` / Opacity : `0.18`

**Comment by aloisdeniel** [comment]
Maybe without background image ?

<img width="514" alt="screen shot 2017-10-05 at 01 33 29" src="https://user-images.githubusercontent.com/7687231/31204688-3aa08f9a-a96d-11e7-933b-0859c6358bdf.png">

**Comment by jamesmontemagno** [comment]
I very much like this! background images are tough if not on mobile IMHO

**Comment by aloisdeniel** [comment]
So let's do the second one, PR is coming very soon!

**Comment by jamesmontemagno** [comment]
![image](https://user-images.githubusercontent.com/1676321/31290614-f68222fe-aa81-11e7-8f82-9229ec7502e6.png)



Via mobile center :)

**Comment by jamesmontemagno** [comment]
I think the button text may be a bit long though on smaller device. 

Would do:
MVP Sign In
Learn About Program

**Comment by aloisdeniel** [comment]
Great! Having Mobile Center configured will help! You’re right about text length, I’ll change.
