### ISSUE TITLE
[Bug] Login problems

### ISSUE THREAD

**Issue by sthewissen** [Microsoft/mvp#45]
A few things are going wrong with the login now:

- The SKIP_LOGIN doesn't work anymore. The following line crashes:
https://github.com/Microsoft/mvp/blob/dev/MVP/MVPUI/CustomControls/MVPNavigationPage.cs#L18

This is due to the fact that a `Color` is expected but it receives a `OnPlatform<Color>` right now.

- For the MVP people that sign in through the actual LiveID login the following line is problematic:
https://github.com/Microsoft/mvp/blob/dev/MVP/MVPUI/LiveIdLogOn.xaml.cs#L66

This only shows a modal instance of the MyProfile page. No tabs, no way to get to the activities :)

**Comment by sthewissen** [comment]
I've fixed these for now in #46. However, the first one isn't really fixed yet. I commented it out for now because we need to find a common ground for this. Some colors defined in the App.xaml are defined simply as colors and some are using OnPlatform. We probably don't want to code this in a way where you need to guess what to cast it to each time you use a color. Any smart idea on how to standardize this @jamesmontemagno or others?

The second one should be fixed but I can't test it since I have no valid MVP Live ID to test it with.

**Comment by Depechie** [comment]
Had the same issues as @sthewissen when trying out some new c# code refactoring.
Just weird that there is a different way of navigation when you're using the LiveIdLogOn page.

**Comment by jamesmontemagno** [comment]
I'll fix it up :)
