### ISSUE TITLE
[Design] Current + New Design Specification

### ISSUE THREAD

**Issue by jamesmontemagno** [Microsoft/mvp#5]
Would be nice to have the design team do a 1 over on it.

New thoughts here based on what I am seeing to mock up:

- Tabbed Page for MainHome
- 2 Tabs -> Profile + Contributions (Top on Android/UWP, Bottom on iOS)
- NavigationPage as the root on Android/UWP, TabbedPage as Root + NavigationPages inside of each Tabbed Page
- Profile Page to have a Info button in the top right -> brings to an about page to log out/read about the app
- Contributions has a list of contributions, top right icon is a + to add new contributions

**Comment by scottge-msft** [comment]
For lack of designer resource when we develop this app, I (PM) did the design by myself unfortunately :)
Here is the design of the app:
https://projects.invisionapp.com/share/5C88RUBHZ#/screens

**Comment by Depechie** [comment]
@jialge It seems the iOS app and the referenced design don't match very much for the moment.

Not sure what would be the best option to 'go forward' on this, because each person will have a different view on how the design would need to look, but it would be great if the current version could be upgraded a bit :)
James mentioned that the last Evolve app had a nice speaker page layout that maybe can be retrofitted for the profile page... ?

**Comment by sthewissen** [comment]
Im more than willing to help with the design, I can look into it a bit more tomorrow (past midnight here now).

**Comment by Depechie** [comment]
At least on iOS version my own profile is front and centre. That is not needed ( I know who I am :D ).
So please put it away in a separate tab or something.

So for me the activity list would need to be the first thing I see and a fast ADD ( + ) button should be prominent. ( to enter new activities )

**Comment by sthewissen** [comment]
@jamesmontemagno I've just messed around a bit on the iOS side of things to get the navigation looking slick. Took the iOS Outlook app as a base. I haven't gone near the profile page content itself yet. Don't seem to have the right to start a PR though :(

![demo](https://user-images.githubusercontent.com/2419439/30751625-28316fa8-9fba-11e7-8c43-4dbfe8c1be2e.png)

**Comment by jamesmontemagno** [comment]
I think this is a good first step here.

I think that for Android/UWP we have the blue title navigation bar up top on pages and iOS look like an iOS application.

All Modal pages should be wrapped in a navigation page with a way to exit it on the top right.

On iOS it should say : Close or Done based on the use case
Android/UWP: should have an icon

**Comment by sthewissen** [comment]
On iOS a "multiply" icon to close a modal is becoming more and more accepted. Stylistically I think it would look better than a text version. A lot of Microsoft's own apps do it as well (e.g. Outlook) which is why I included it.

**Comment by jamesmontemagno** [comment]
I added some design here: https://github.com/Microsoft/mvp/blob/master/MobileAppGuidelines.md

I think we should follow Apple's guidelines and they use "Close" or "Done" if editing: https://developer.apple.com/ios/human-interface-guidelines/user-interaction/data-entry/
