### ISSUE TITLE
[Question] Application Feature Specification Document

### ISSUE THREAD

**Issue by jamesmontemagno** [Microsoft/mvp#6]
Do you have a list of the features that the application should have built into it. I am trying to figure out why some of the packages are in there.

Even if a small bullet list.

**Comment by scottge-msft** [comment]
Here are the features for this 1.0 version of the app:

1) MVP can sign in 
2) MVP can view his/her profile info (name, bio, photo, award category)
3) MVP can view, edit, and submit contributions
