### ISSUE TITLE
replace “Activity” with “Contribution”

### ISSUE THREAD

**Issue by seiya1223** [Microsoft/mvp#70]
We need to replace “Activity” with “Contribution” in the source code.

**Comment by jfversluis** [comment]
Activities was chosen earlier on to be consistent with the Microsoft MVP web portal.

**Comment by jamesmontemagno** [comment]
@seiya1223 is there a specific requirement here. we just synced with the site.

**Comment by seiya1223** [comment]
This is a requirement from the business team before we open source the code.

**Comment by jamesmontemagno** [comment]
Are they going to change it on the website, I don't see any problem with it being Activities if that is what the website says.   @jialge  can maybe confirm here.

**Comment by scottge-msft** [comment]
The site was using 'Activity' a long time ago, and we were replacing all 'Activity' with 'contribution' after the business team discussion.   We want to consistently use 'contribution' going forward.  so please replace all with 'Contribution'
