### ISSUE TITLE
if we save contribution failed, it didn’t show any error message.

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/mvp#79]
In contribution detail page, if we save contribution failed, it didn’t show any error message.
![contributiondetail](https://user-images.githubusercontent.com/15098626/32584783-18968c4a-c535-11e7-8d6c-9ed923e6a9db.png)

**Comment by jamesmontemagno** [comment]
so, on the site it says that we can only edit/submit new ones for a certain date... is this information returned somewhere?

**Comment by jamesmontemagno** [comment]
Also, when you hit save does anything happen?

**Comment by seiya1223** [comment]
@jamesmontemagno The information will be returned from the response content( Saved in the MyProfileViewModel.Instance.ErrorMessage)
![image](https://user-images.githubusercontent.com/8097597/32706660-da1102fc-c859-11e7-9676-2089d29437d7.png)
We just need to check the error message while call the AddContributionModel service.
![image](https://user-images.githubusercontent.com/8097597/32706700-0d9c0cfc-c85a-11e7-9134-5a40eabaa68d.png)

In our previous design, we show this message to a label on the top of the ContributionDetail page and we prepare to show it by UserDialogs too.
