### ISSUE TITLE
[Feature] Show MVP account number

### ISSUE THREAD

**Issue by Depechie** [Microsoft/mvp#9]
Would be great if our MVP account number would be shown on the profile page...

**Comment by scottge-msft** [comment]
Sounds great!  We will get this done :)

**Comment by sthewissen** [comment]
Added it to the alternative design I posted in #21.

**Comment by sthewissen** [comment]
Is it possible to debug using PRD data instead of our mocked data? That would be nice to implement this since this number isn't available yet through the current API connection.

**Comment by Depechie** [comment]
Seems DEV branch has this feature already available... so for me this issue may be closed.
Or how do you handle the v1 todo list @jamesmontemagno ?

**Comment by sthewissen** [comment]
Does it also give you your actual number now? Not sure if my previous comment ever got worked into the dev version :)

**Comment by Depechie** [comment]
Just had to do a small fix and yes the number is now showing up :)
https://github.com/Microsoft/mvp/pull/48

**Comment by sthewissen** [comment]
Great! Then this can be closed indeed.
